image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10.13.0

cache:
  - node_modules -> yarn.lock
  - '%USERPROFILE%\.electron -> package.json'

init:
  - git config --global core.autocrlf input

install:
  - ps: Update-NodeJsInstallation $Env:nodejs_version $Env:PLATFORM
  - node --version
  - yarn --version
  - yarn --frozen-lockfile --non-interactive

build: off

test_script:
  - yarn lint:js
  - yarn test

after_test:
  - yarn cross-env NODE_ENV=production ember electron:build -e production
  - ps: |
      $path = "$Env:PATH;C:\Program Files (x86)\Windows Kits\10\App Certification Kit"
      Set-AppveyorBuildVariable -Name 'PATH' -Value $path
      $cscFile = Join-Path -Path "$Env:TMP" -ChildPath csc.p12
      [IO.File]::WriteAllBytes($cscFile, [Convert]::FromBase64String($Env:CSC_LINK))
      Set-AppveyorBuildVariable -Name 'CSC_FILE' -Value $cscFile
  - yarn cross-env NODE_ENV=production ember electron:make -e production --build-path electron-out/ember
  - ps: Remove-Item -Path $Env:CSC_FILE

artifacts:
- path: electron-out\make\*.zip
  name: zip
- path: electron-out\make\squirrel.windows\$(PLATFORM)\*.exe
  name: exe
- path: electron-out\make\squirrel.windows\$(PLATFORM)\*.nupkg
  name: nupkg
- path: electron-out\make\squirrel.windows\$(PLATFORM)\RELEASES
  name: releases

before_deploy:
  - ps: |
      $package = Get-Content -Raw -Path package.json | ConvertFrom-Json
      $release = "$($package.productName) $($Env:APPVEYOR_REPO_TAG_NAME.Substring(1))"
      Set-AppveyorBuildVariable -Name 'GITHUB_RELEASE' -Value $release

deploy:
  - provider: GitHub
    auth_token: $(GITHUB_TOKEN)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(GITHUB_RELEASE)
    artifact: zip, exe, nupkg, releases
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
